from __future__ import annotations


class SearchQueryCatalog:
    """Broad, lawful source-discovery queries for real asset/value paths."""

    SIMPLE_DIRECT_GAIN_QUERIES = [
        "official free sample request form shipped no purchase",
        "free sample box application shipping address official",
        "product testing panel keep products application official",
        "free product tester application shipped official",
        "paid user testing tester signup PayPal official",
        "website testing paid tester signup official",
        "paid research participant signup PayPal gift card official",
        "user interviews paid research participant signup official",
        "beta tester rewards gift card application official",
        "app beta tester rewards gift card official",
        "gift card rewards signup bonus no purchase official",
        "cashback rewards signup bonus no deposit official",
        "brand sample request form no purchase official",
        "free merchandise testing program application official",
        "no purchase giveaway official entry form prize",
    ]

    FAST_DIRECT_GAIN_QUERIES = [
        "open settlement claim form cash no proof required deadline official",
        "data breach settlement cash claim form open no proof required",
        "official claim administrator submit claim cash payment open",
        "current class action settlement claim form cash deadline no proof",
        "official rebate claim form prepaid card no purchase required",
        "official refund claim form cash payment open",
        "official product recall reimbursement claim form cash",
        "state unclaimed property official claim money search",
        "paid research study remote PayPal signup official",
        "paid website testing PayPal tester signup official",
        "paid user interview gift card remote signup official",
        "free sample request form shipped official brand",
        "free product testing application keep products shipped official",
        "free full size product tester panel official application",
        "gift card rewards no purchase signup bonus official",
        "creator rewards payout application official no purchase",
        "developer bounty payout open source official",
        "startup credits application cloud AI official founder",
        "crypto learn earn rewards no deposit official",
        "web3 quest rewards public wallet no purchase official",
    ]

    DEFAULT_QUERIES = [
        "official refund claims open settlement cash payment",
        "consumer settlement claim form gift card refund",
        "official consumer rebate claim form cash back no purchase required",
        "manufacturer rebate claim form prepaid card official",
        "class action settlement claim form no proof required open",
        "FTC refund program claim deadline open",
        "state unclaimed property claim portal official money",
        "free product testing items shipped application",
        "free samples by mail official brand application",
        "official product testing panel free full size products shipped",
        "brand ambassador sampling program free product application",
        "home product tester panel free samples application",
        "beauty product testing free samples application official",
        "baby product testing free samples shipped application",
        "pet product testing free samples shipped application",
        "food product testing free samples shipped application",
        "electronics product testing free review program application",
        "free merchandise testing program application official",
        "free pallets liquidation samples local pickup no purchase",
        "developer credits startup cloud credits application",
        "AI credits startup program application",
        "software license free developer program credits",
        "open source maintainer credits free cloud AI developer program",
        "student founder startup credits free cloud software AI",
        "rebate finder appliance electronics cash back",
        "official prize challenge competition open application",
        "no purchase necessary sweepstakes prize official rules claim",
        "creator fund payout program application",
        "creator rewards beta program payout application official",
        "short video creator incentive program payout application",
        "affiliate program instant payout official",
        "referral bonus program PayPal payout no purchase official",
        "cashback rewards signup bonus no deposit official",
        "gift card rewards program signup bonus no purchase official",
        "survey panel PayPal payout low effort official",
        "paid research study online PayPal gift card application",
        "online focus group paid study application official",
        "user testing paid website test application official",
        "app beta testing rewards gift card application",
        "software beta tester rewards application official",
        "bug bounty swag rewards low risk program official",
        "grant prize challenge funding open applications",
        "unclaimed property claim portal official",
        "unclaimed retirement benefits search claim",
        "savings bond treasury hunt claim",
        "free NFT airdrop official no wallet signing no purchase",
        "crypto learn and earn rewards no deposit official",
        "official crypto airdrop quest no purchase no wallet signing",
        "web3 quest rewards official no purchase public wallet only",
        "developer bounty payout open source official",
        "free nft claim official no purchase no seed phrase",
        "retroactive public goods rewards grants official",
        "startup founder grant cloud credits AI credits official",
        "web3 grant bounty rewards no purchase official",
        "local free items pickup official community",
        "free furniture pickup local official nonprofit program",
        "free building materials reuse center local pickup",
        "free food assistance benefits application official",
        "student developer pack free credits software",
        "startup credits cloud AI developer program",
        "free event ticket giveaway official no purchase required",
        "free museum pass library program official",
        "free membership credit official application",
        "open call product reviewer free sample application",
        "early access reward program application official",
        "CFPB payments harmed consumers current cases refund claim",
        "SEC distributions harmed investors claim administrator open",
        "court approved settlement administrator claim form open no proof",
        "open class action settlements no proof purchase required deadline",
        "data breach settlement cash claim open no proof required",
        "product testing community keep products free sign up official",
        "beauty product tester panel full size products official sign up",
        "home goods product tester free product review panel",
        "food product testing panel free samples shipped official",
        "paid research participant PayPal studies sign up official",
        "paid user interview research studies remote PayPal official",
        "website usability testing paid tester sign up official",
        "mobile app beta tester rewards gift card official",
        "startup software credits founder deals official application",
        "cloud credits startup program apply founder official",
        "AI startup credits compute credits apply official",
        "open source bounty rewards developer payout official",
        "hackathon prize competition open deadline developer official",
        "data science competition prize open deadline official",
        "web3 quest public wallet rewards no purchase official",
        "crypto learn earn rewards no deposit official",
        "airdrop eligibility checker official public wallet no seed phrase",
        "grant program founder prize challenge apply official",
        "reimbursement claim form official product recall cash",
        "recall settlement reimbursement claim official",
        "free sample box application shipping address official",
    ]

    @classmethod
    def get_queries(cls, configured: list[str] | None = None, limit: int = 8) -> list[str]:
        queries = configured or [*cls.SIMPLE_DIRECT_GAIN_QUERIES, *cls.FAST_DIRECT_GAIN_QUERIES, *cls.DEFAULT_QUERIES]
        deduped: list[str] = []
        seen: set[str] = set()
        for query in queries:
            cleaned = " ".join(str(query).split())
            if not cleaned or cleaned.lower() in seen:
                continue
            seen.add(cleaned.lower())
            deduped.append(cleaned)
            if len(deduped) >= limit:
                break
        return deduped
